apiVersion: v1
kind: Service
metadata:
  name: accounts-coll-0b53895248604867baf743ac0ff350dc-srv
spec:
  selector:
    app: accounts-coll-0b53895248604867baf743ac0ff350dc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
  type: ClusterIP